name: build

on:
  push:

jobs:
  Build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: exordos/exordos_ci/.github/workflows/element_build.yml@master
    secrets:
      PUSH_CFG: ${{ secrets.PUSH_CFG }}
