name: tests

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.markdownlint.yaml'
  pull_request:
    types: [opened]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.markdownlint.yaml'

jobs:
  Tests:
    uses: exordos/exordos_ci/.github/workflows/python_tests.yml@master
    with:
      apt-packages: libev-dev libvirt-dev
  Functional:
    uses: exordos/exordos_ci/.github/workflows/python_tests.yml@master
    with:
      apt-packages: libev-dev libvirt-dev
      lint-envs: ""
      coverage-envs: ""
      test-env-suffix: -functional
      postgres-db: exordos_notification
